### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by kelvinji2009** [virl/underdark-ios#1]
# How to reproduce the bug

//run android app and iOS app, auto discovery and auto connect properly

//make android phone suspended and keep iOS app run foreground->iOS app `Terminating app due to uncaught exception 'NSInvalidArgumentException'`

2015-11-04 14:49:38.637 UDApp[712:253935] -[__NSArrayM repeats]: unrecognized selector sent to instance 0x144580920
2015-11-04 14:49:38.644 UDApp[712:253935] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArrayM repeats]: unrecognized selector sent to instance 0x144580920'
**\* First throw call stack:
(0x185c48f48 0x19a70bf80 0x185c4fc5c 0x185c4cc00 0x185b50cac 0x100148048 0x100147e64 0x1000fcf1c 0x100127ca8 0x101345ca8 0x101345c68 0x101352780 0x101349958 0x101354898 0x101354590 0x19b13d470 0x19b13d020)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

//revoke android app to foreground, rerun iOS app->the iOS app goes to dead connection loop and then crashed

//log
nodeId=4334988448390341065
transport started.

link connected.
++++nodeId=7491551514539095048
link connected.
++++nodeId=1432052332777346693
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=6085572795618208438
link disconnected.
----nodeId=6085572795618208438
link connected.
++++nodeId=7491551514539095048
link connected.
++++nodeId=6085572795618208438
link disconnected.
----nodeId=7491551514539095048
link disconnected.
----nodeId=6085572795618208438
link connected.
++++nodeId=6085572795618208438
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=6085572795618208438
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=6085572795618208438
link disconnected.
----nodeId=6085572795618208438
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=6085572795618208438
link disconnected.
----nodeId=6085572795618208438
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=7491551514539095048
link connected.
++++nodeId=6085572795618208438
link disconnected.
----nodeId=7491551514539095048
link disconnected.
----nodeId=6085572795618208438
link connected.
++++nodeId=7491551514539095048
link connected.
++++nodeId=6085572795618208438
link disconnected.
----nodeId=6085572795618208438
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=7491551514539095048
link connected.
++++nodeId=7491551514539095048
link disconnected.
----nodeId=7491551514539095048
(lldb) 

Thread 12Queue : Underdark Transport (serial)
#0  0x000000019a71dbd0 in objc_msgSend ()
#11 0x000000019b13d470 in _pthread_wqthread ()

Enqueued from com.apple.root.default-qos.overcommit (Thread 6)Queue : com.apple.root.default-qos.overcommit (serial)
#0  0x00000001013e15f0 in _dispatch_barrier_async_f_slow ()
#22 0x000000019b13d028 in thread_start ()

libobjc.A.dylib`objc_msgSend:
    0x19a71dbc0 <+0>:   cmp    x0, #0
    0x19a71dbc4 <+4>:   b.le   0x19a71dc2c               ; <+108>
    0x19a71dbc8 <+8>:   ldr    x13, [x0]
    0x19a71dbcc <+12>:  and    x9, x13, #0x1fffffff8
->  0x19a71dbd0 <+16>:  ldp    x10, x11, [x9, #16]
    0x19a71dbd4 <+20>:  and    w12, w1, w11
    0x19a71dbd8 <+24>:  add    x12, x10, x12, lsl #4
    0x19a71dbdc <+28>:  ldp    x16, x17, [x12]
    0x19a71dbe0 <+32>:  cmp    x16, x1
    0x19a71dbe4 <+36>:  b.ne   0x19a71dbec               ; <+44>
    0x19a71dbe8 <+40>:  br     x17
    0x19a71dbec <+44>:  cbz    x16, 0x19a71dd80          ; _objc_msgSend_uncached_impcache
    0x19a71dbf0 <+48>:  cmp    x12, x10
    0x19a71dbf4 <+52>:  b.eq   0x19a71dc00               ; <+64>
    0x19a71dbf8 <+56>:  ldp    x16, x17, [x12, #-16]!
    0x19a71dbfc <+60>:  b      0x19a71dbe0               ; <+32>
    0x19a71dc00 <+64>:  add    x12, x12, w11, uxtw #4
    0x19a71dc04 <+68>:  ldp    x16, x17, [x12]
    0x19a71dc08 <+72>:  cmp    x16, x1
    0x19a71dc0c <+76>:  b.ne   0x19a71dc14               ; <+84>
    0x19a71dc10 <+80>:  br     x17
    0x19a71dc14 <+84>:  cbz    x16, 0x19a71dd80          ; _objc_msgSend_uncached_impcache
    0x19a71dc18 <+88>:  cmp    x12, x10
    0x19a71dc1c <+92>:  b.eq   0x19a71dc28               ; <+104>
    0x19a71dc20 <+96>:  ldp    x16, x17, [x12, #-16]!
    0x19a71dc24 <+100>: b      0x19a71dc08               ; <+72>
    0x19a71dc28 <+104>: b      0x19a71dd80               ; _objc_msgSend_uncached_impcache
    0x19a71dc2c <+108>: b.eq   0x19a71dc44               ; <+132>
    0x19a71dc30 <+112>: adrp   x10, 29364
    0x19a71dc34 <+116>: add    x10, x10, #816
    0x19a71dc38 <+120>: lsr    x11, x0, #60
    0x19a71dc3c <+124>: ldr    x9, [x10, x11, lsl #3]
    0x19a71dc40 <+128>: b      0x19a71dbd0               ; <+16>
    0x19a71dc44 <+132>: movz   x1, #0
    0x19a71dc48 <+136>: movi   d0, #0000000000000000
    0x19a71dc4c <+140>: movi   d1, #0000000000000000
    0x19a71dc50 <+144>: movi   d2, #0000000000000000
    0x19a71dc54 <+148>: movi   d3, #0000000000000000
    0x19a71dc58 <+152>: ret  
    0x19a71dc5c <+156>: nop

**Comment by virl** [comment]
@kelvinji2009 Thanks, will look into it.

**Comment by virl** [comment]
@kelvinji2009 Can't reproduce the bug. Specifically, what you mean by "make Android app suspended"?

**Comment by kelvinji2009** [comment]
@virl sorry, i mean "make Android phone suspend"(take underdark android app in background and push the power button make the android phone suspend).

**Comment by kelvinji2009** [comment]
@virl My test environment is:
Nexus4 Android 5.1.1
iPhone5s iOS9.1

**Comment by virl** [comment]
@kelvinji2009 Thanks, I'll try to reproduce this bug tomorrow.

**Comment by kelvinji2009** [comment]
@virl Thanks. I just test the objc-example and got the same issue.

**Comment by virl** [comment]
@kelvinji2009 objc example is exactly the same and uses same library binary — don't bother testing it.

**Comment by kelvinji2009** [comment]
@virl Yes and thank you in advance.

**Comment by virl** [comment]
@kelvinji2009 Still can't reproduce the bug. If you're still experimenting with the library, can you please capture short video of it?

**Comment by virl** [comment]
@kelvinji2009 I've reproduced the bug. Fix is on the way.

**Comment by kelvinji2009** [comment]
@virl Cool and thanks. ^_^

**Comment by virl** [comment]
@kelvinji2009 I've published fixed version for iOS. Also I have new distribution mechanism, so now instead of downloading from github repository, please download iOS version from Bintray: https://bintray.com/underdark/ios/underdark/

On Android repository name is also changed (but no new versions yet).

This bug was actually three bugs — two on iOS (crash+constant reconnect) and one on Android (inability to connect when in sleep mode). iOS ones seems to be fixed, Android one will be fixed later.

**Comment by virl** [comment]
@kelvinji2009 Please check and tell me is bug fixed for you.

**Comment by kelvinji2009** [comment]
@virl I had test many times and can't reproduce it any more. Nice work! Thank you very much.

**Comment by virl** [comment]
@kelvinji2009 Glad to hear!

**Comment by kelvinji2009** [comment]
@virl But still not very stable for now when one peer disconnected.Sometimes, only one connected, but iOS UDApp displayed more than one peer connected.

**Comment by virl** [comment]
@kelvinji2009 I know. Currently I'm totally rewriting the iOS connection engine using more low-level system API — it will work much better soon.

**Comment by kelvinji2009** [comment]
@virl Okay. Thank you. I can go forward now.
